
<tr class="active">
    <th scope="row" class="check-column" style="border-left-color: #ffb900; background-color: #fff8e5;"></th>
    <td class="plugin-title column-primary colspanchange update-message" colspan="2" style="background-color: #fff8e5;">
        <p style="display: flex; align-items: center; margin: 0;">
            <span style="padding-left: 6px;">
                The object cache drop-in is outdated and should be updated to <?php echo $this->version; ?>.
                <a href="https://objectcache.pro/docs/must-use-plugin/">Learn more</a>.
            </span>
        </p>
    </td>
</tr>
