
The object cache drop-in did not log any commands.
You may enable logging by setting the <code>`SAVEQUERIES`</code> or <code>`WP_DEBUG`</code> constant to <code>true</code>.
<br />
<br />
Alternatively you can set <code>`save_commands`</code> or <code>`debug`</code> configuration option to <code>true</code> in your <code>`WP_REDIS_CONFIG`</code>.
<a href="https://objectcache.pro/docs/logging/" target="_blank">Read about logging</a>.
