<div class="objectcache:widget objectcache:groups-widget">
    <p>
        Run a cache scan to see a list of all groups currently present in the cache.
        This may take a while.
    </p>

    <div class="actions">
        <button class="button button-secondary" data-text="Scan groups" data-loading="Scanning...">
            Scan groups
        </button>

        <button class="button button-tertiary hidden" data-text="Copy to clipboard" data-copied="Copied!" data-clipboard-target=".objectcache\:groups-widget .table-container">
            Copy to clipboard
        </button>
    </div>
</div>
